# ASP.NET Core
# Build and test AST.NET core projects targeting .NET croe
# Add seps that run tests, create a NuGet package, deploy and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 18.04'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: '2.2.401'
  - script: dotnet build ./SimpleCommerce.sln
    displayName: 'dotnet build'
  - script: /run-tests.sh
    displayName: 'run tests'
  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/*.trx'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.trx'